WET-255 - GC Task Success Survey: Survey Referrer value being cut-off
ServiceCanada/invitation-manager pull request #18
Opened 2023-06-13 14:36 UTC by Ricokola

- Finding an alternative for providing the referrer path following the domain name.
- Using `window.location.pathname` to fetch everything following the domain name and add it pass it via a URL parameter.
- From the task success survey, fetching the URL parameter and concatenate it  to the domain name in `document.referrer`.

Working example: https://ricokola.github.io/invitation-manager/docs/test-IM/test-eng.html?logim=1&im_scope=Page&im_surveyid=4&im_nocookiecheck=1&im_nodatecheck=1

2023-06-13 17:56 UTC, Ricokola commented
@GormFrank or @duboisp Can you please review this PR.

Note: This is set for the working example. As soon it's approved, I will adjust to reflect the Service Canada example.

2023-07-07 17:17 UTC, GormFrank requested changes

2023-07-07 17:17 UTC, GormFrank commented on docs/config.JSON
> +{ "dbURL": "/invitation-manager/docs/im3.json",
Please keep im.json here

2023-07-07 17:17 UTC, GormFrank commented on docs/im2.json
> +﻿{
No need for this file, just update im.json if needed

2023-07-07 17:17 UTC, GormFrank commented on docs/im3.json
> +﻿{
No need for this file.

2023-07-07 17:17 UTC, GormFrank commented on docs/test-IM/test-eng.html
> +	<link rel="stylesheet" href="https://ricokola.github.io/invitation-manager/src/Overlay.css">
Please keep the servicecanada URL

2023-07-07 17:17 UTC, GormFrank commented on docs/test-IM/test-eng.html
> +		window.imConfigPath = "https://ricokola.github.io/invitation-manager/docs/";
Please keep the servicecanada URL, and update the docs location if needed

2023-07-07 17:17 UTC, GormFrank commented on docs/test-IM/test-eng.html
> +	<script src="https://ricokola.github.io/invitation-manager/src/Overlay.js"></script>
Please keep the servicecanada URL, and update the Overlay.js file as needed, and the InvitiationManager.js as needed. We want to track the changes here.

2023-07-07 17:17 UTC, GormFrank commented on docs/test-IM/test-eng.html
> +	<script src="https://ricokola.github.io/invitation-manager/src/InvitationManager-eric.js"></script>
Idem

2023-07-07 17:17 UTC, GormFrank commented on src/InvitationManager-eric.js
> +/*
This file is not needed, please update the InvitationManager.js file as needed instead.

2023-08-01 17:47 UTC, Ricokola commented
@GormFrank Propsoed changes have been made and PR has been updated accordingly. Please review and let me konw !

2023-08-03 20:07 UTC, GormFrank requested changes
One small remaining change

2023-08-03 20:07 UTC, GormFrank commented on docs/test-IM/test-eng.html
> +		<script src="https://servicecanada.github.io/invitation-manager/src/InvitationManager-eric.js"></script>
This still has `-eric` in the link:
```suggestion
		<script src="https://servicecanada.github.io/invitation-manager/src/InvitationManager.js"></script>
```

2023-10-05 13:51 UTC, GormFrank approved these changes

2023-10-05 13:51 UTC, merged